export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';

export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';

export const SHOW_COMMENTS_START = 'SHOW_COMMENTS_START';
export const SHOW_COMMENTS_SUCCESS = 'SHOW_COMMENTS_SUCCESS';
export const SHOW_COMMENTS_FAIL = 'SHOW_COMMENTS_FAIL';